name: myexp1transfo
dataset:
  proto: TextDatasetTransfo
  root: data/mediaca
  src: findings.tok
  tgt: impression.tok
  max_len: 80
  use_bucket: false

model:
  proto: Transformer

  encoder:
    proto: TransformerEncoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    vocab_size: 8769 # findings
    dropout_emb: 0.0
    dropout_r: 0.2

  decoder:
    proto: TransformerDecoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    vocab_size: 7167 # impression
    dropout_ctx: 0.0
    dropout_out: 0.0
    dropout_r: 0.2



train:
  proto: NMTTrainer
  device: cuda
  lr: 0.0004
  weight_decay: 0.00001 #1e-05
  batch_size: 64
  lr_decay_factor: 0.5
  lr_decay_patience: 2
  lr_min: 0.000001
  epochs: 99
  early_stop: 10


validator:
  proto: NMTValidator
  device: cuda
  batch_size: 16
  beam_width: 12
  splits: [dev]

ensemblor:
  proto: NMTEnsemblor
  device: cuda
  batch_size: 16
  beam_width: 12
  splits: [dev]
  mode: all # best,all
