name: myexp1
dataset:
  proto: TextDatasetTransfo
  root: data/mediaca
  src: findings.tok
  tgt: impression.tok

model:
  proto: Transformer

  encoder:
    proto: TransformerEncoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    vocab_size: 8769 # findings
    dropout_emb: 0.4
    dropout_r: 0.1

  decoder:
    proto: TransformerDecoder
    model_dim: 512
    ffn_dim: 2048
    layers: 6
    heads: 8
    vocab_size: 7167 # impression
    dropout_ctx: 0.5
    dropout_out: 0.5
    dropout_r: 0.1

train:
  proto: NMTTrainer
  device: cuda
  lr: 0.0001
  weight_decay: 0.00001 #1e-05
  batch_size: 32
  lr_decay_factor: 0.5
  lr_decay_patience: 2
  lr_min: 0.000001
  epochs: 99
  early_stop: 10


validator:
  proto: NMTValidator
  device: cuda
  batch_size: 16
  beam_width: 1
  splits: [dev]
  max_len: 80

ensemblor:
  proto: NMTEnsemblor
  device: cuda
  batch_size: 16
  beam_width: 5
  splits: [dev]
  max_len: 80
  mode: all # best,all
