name: myvqg
dataset:
  proto: VQGDataset
  root: data/2020-VQG
  image_path: data/2020-VQG/images
  src: q.txt
  tgt: q.txt
  images: ids.txt
  max_len: 50
  eval_max_len: 50
  load_memory: False

model:
  proto: RNN
  encoder:
    proto: CNN
    backbone: resnet50
    output_layer: layer3
    dropout_out: 0.1
    ctx_size: 1024

  decoder:
    proto: ConditionalDecoder
    input_size: 200
    hidden_size: 512
    n_vocab: 2035 # impression
    rnn_type: GRU
    tied_emb: True
    dec_init: zero
    dec_init_activ: tanh
    dec_init_size: None
    att_type: mlp
    att_activ: tanh
    att_bottleneck: hid
    att_temp: 1.0
    transform_ctx: True
    mlp_bias: False
    dropout_out: 0.1


train:
  proto: NMTTrainer
  device: cuda
  lr: 0.00005
  weight_decay: 0.00001 #1e-05
  batch_size: 16
  lr_decay_factor: 0.5
  lr_decay_patience: 2
  lr_min: 0.000001
  epochs: 99
  early_stop: 10
  eval_start: 0
  metrics: [ROUGE, BLEU, METEOR]
  early_stop_metric: METEOR

validator:
  proto: NMTValidator
  device: cuda
  batch_size: 16
  beam_width: 2
  splits: [val]

ensemblor:
  proto: NMTEnsemblor
  device: cuda
  batch_size: 16
  beam_width: 2
  splits: [val]
  mode: all # all ou best-n
